version: '3.7'
services:
  postgresql:
    container_name: 4wheel-db
    image: postgres:15
    tty: true
    environment:
      POSTGRES_USER: c2tx420
      POSTGRES_PASSWORD: Abcd1234
      POSTGRES_DB: 4wheel
    ports:
      - 5432:5432
    volumes:
      - ./dbdata/:/var/lib/postgresql/data
